### ISSUE TITLE
xvi doesn't build with gcc on AIX 7.1

### ISSUE THREAD

**Issue by martinwguy** [martinwguy/xvi#28]
On gcc111 of the GCC Compile Farm, AIX 7.1, building fails immediately:

```
-bash-4.3$ make CC=gcc -f makefile.aix    # gcc111 doesn't have "cc"
        gcc -DUNIX -DAIX -DTERMIO  -c -o alloc.o alloc.c
In file included from /opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/4.8.1/include-fixed/fcntl.h:234:0,
                 from unix.h:30,
                 from xvi.h:673,
                 from alloc.c:23:
/opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/4.8.1/include-fixed/unistd.h:191:14: error: conflicting types for 'getcwd'
 extern char *getcwd(char *, size_t);
              ^
In file included from alloc.c:23:0:
xvi.h:108:19: note: previous declaration of 'getcwd' was here
     extern  char *getcwd P((char *, unsigned));
                   ^
In file included from /opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/4.8.1/include-fixed/fcntl.h:234:0,
                 from unix.h:30,
                 from xvi.h:673,
                 from alloc.c:23:
/opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/4.8.1/include-fixed/unistd.h:227:21: error: conflicting types for 'sleep'
 extern unsigned int sleep(unsigned int);
                     ^
In file included from alloc.c:23:0:
xvi.h:109:18: note: previous declaration of 'sleep' was here
     extern  void sleep P((unsigned seconds));
                  ^
make: 1254-004 The error code from the last command is 1.


Stop.
```

**Comment by martinwguy** [comment]
In progress, see 481cf542b

**Comment by martinwguy** [comment]
Works now on AIX using makefile.aix
